### ISSUE TITLE
alternate registers

### ISSUE THREAD

**Issue by markcohen32** [SystemRDL/PeakRDL-ipxact#17]
Hi,

I have a question about the parsing of the IP-XACT file. I have a field called "alternate registers" - is it supposed to be parsed? how does the parser treats it? currently it looks like it ignores it.

Thanks.

**Comment by amykyta3** [comment]
The IP-XACT importer does its best to transcribe the XML into SystemRDL concepts. Unfortunately the IP-XACT feature set does not perfectly overlap with SystemRDL concepts, so there are some things that cannot be faithfully represented in SystemRDL concepts and are ignored. The `alternateRegisters` element is one of these concepts that do not really have a good counterpart in RDL, so it is ignored.

For more details, see: https://peakrdl-ipxact.readthedocs.io/en/latest/importer.html

**Comment by hughjackson** [comment]
It could be useful if the importer handled the special case of one read-only and one write-only register. This is supported in the SystemRDL spec and is sometimes used to differentiate access to transmit and receive FIFOs at the same address
