### ISSUE TITLE
IPXACT importer is arraying registers when it is not required.

### ISSUE THREAD

**Issue by willy134** [SystemRDL/PeakRDL-ipxact#20]
I have some IPXACT files that are from 3rd party ip with the register/dim value set to 1.  Looking at the ipxact documentation this is the default.  PeakRDL interprets this as an arrayed register with dimension of 1, which is kind of correct, but when I dump the html documentation the register is shown with the array square brackets[].

It would be nice if the ipxact importer checked the size of the dimension before turning the register into an arrayed register.  I did a quick hack of changing:
`if 'dim' in d:`
to
` if 'dim' in d and d['dim'][0] > 1:`

That did remove the extra array indicators.  However, I am pretty sure that is not the appropriate way to actually fix this.

**Comment by amykyta3** [comment]
> Looking at the ipxact documentation this is the default

Can you point me to where you see that? I checked the spec and it shows the `<ipxact:dim>` tag as optional, and that if it is present it implies the node is an array.

**Comment by willy134** [comment]
From the [Accellera IP-XACT User Guide](https://accellera.org/images/downloads/standards/ip-xact/IP-XACT_User_Guide_2018-02-16.pdf) (March 2018), the bottom paragraph of page 28

Copied here:

> A register element describes the software interface to a register. It has a name to identify the element. It can
have a description to provide a human-readable description. A register can have a dim element describing
the dimension of the register. If dim is not described, then its value defaults to 1. Furthermore, a register
has an addressOffset that describes the location of the register expressed in addressUnitBits as offset to the
starting address of the containing addressBlock or the containing registerFile. The size of a register describes
the number of bits in the register. A register size cannot exceed the width of a containing addressBlock. 

Looking at the actual IEEE standard, it isn't as clear.  All I see is that if the node has the array element, dim is mandatory (section C.4.3.2).  It is ambiguous as what should happen if the dim is set to 1.
