### ISSUE TITLE
Announcement: Renaming 'RALBot-ipxact' to 'PeakRDL-ipxact'

### ISSUE THREAD

**Issue by amykyta3** [SystemRDL/PeakRDL-ipxact#4]
See details here: https://github.com/SystemRDL/PeakRDL/issues/2

**Comment by balaskumar** [comment]
Hi all.
In the README, you say:

When an IP-XACT file is imported, the register description is loaded into the SystemRDL register model as if it was an addrmap component declaration. Once imported, the IP-XACT contents can be used as-is, or referenced from another RDL file.

Does this mean that IP-XACT components can be instantiated inside SystemRDL addrmaps? That is a very useful thing to have. Do you have any examples of such usage?

**Comment by amykyta3** [comment]
Yep! its really useful if you need to glue multiple IP-XACT files together from a vendor.
I just uploaded an example. Hope this helps: https://github.com/SystemRDL/PeakRDL-ipxact/tree/master/examples

**Comment by balaskumar** [comment]
Thanks for coming up with that example! Certainly clarifies things for me.
Does this mean that we should be able to convert an IP-XACT register model into a SystemRDL model? All that we would need is to write a SystemRDLExporter. How would one go about writing such a thing?

**Comment by amykyta3** [comment]
Yes it would certainly be possible to export back to SystemRDL.

**Comment by amykyta3** [comment]
Yes it would certainly be possible to export back to SystemRDL.
I'd recommend looking at the compiler's API reference: https://systemrdl-compiler.readthedocs.io/en/latest/
To export, I'm a big fan of using the Jinja template engine. I used it extensively to generate the UVM exporter: https://github.com/SystemRDL/PeakRDL-uvm/tree/master/peakrdl/uvm/templates

Writing an exporter doesn't seem too difficult. I think I could throw one together pretty quickly...
