### ISSUE TITLE
Import IP-XACT with more than 1 memoryMap

### ISSUE THREAD

**Issue by hgdangkhoi** [SystemRDL/PeakRDL-ipxact#6]
Hello,

I have been using your https://github.com/SystemRDL/systemrdl-compiler, and recently found out about this Importer tool to combine with IP-XACT, so thank you for making these tools!

I know this importer only try to import one Memory Map if there are multiple, and the function `seek_to_top_addressBlocks` explains pretty well how you did it. However, I have an IPXACT input that have 2 memoryMap and I want to include both memoryMaps to the compiled object, how would I modify your code to implement this behavior? The `import_file` function basically make one Block the Root Node, and in SystemRDL Compiler I don't think we have the concept of multiple memory maps

EDIT: Feels like the case of 2 memory maps kind of similar to the behavior of the "Bridge" property mentioned in this issue: https://github.com/SystemRDL/systemrdl-compiler/issues/72 , in the `seek_to_top_addressBlocks` I tried to return all the top addrBlock as a list, so in the case of 2 memory maps this function would return 2 top level blocks and I ran into the overlapping error as mentioned in the above "bridge" issue in SystemRDL compiler

**Comment by amykyta3** [comment]
Fixed.
v3.0.0 has now been published.
