### ISSUE TITLE
export systemRDL

### ISSUE THREAD

**Issue by jacobseu2015** [SystemRDL/PeakRDL-ipxact#7]
Hello,
Thanks for your systemRDL tool, now I have a ipxact xml file and import it to the space of systemRDL, how can I export it to systemRDL file？For I need change some register in systemRDL format.

**Comment by amykyta3** [comment]
I currently do not have a tool to export back into SystemRDL

**Comment by mikex-oss** [comment]
Can this be reopened? Or does the FR belong in a different project (e.g. systemrdl-compiler)?

It seems useful, e.g. for migration from other formats or as a SystemRDL generator.

**Comment by mikex-oss** [comment]
Oops, just found https://github.com/SystemRDL/PeakRDL-systemrdl.

**Comment by amykyta3** [comment]
Yep that's it! Several people asked for a way to export SystemRDL,  so I
finally wrote a rudimentary exporter.
